modLoader="javafml"
loaderVersion="[45,)"
issueTrackerURL="https://github.com/CyclopsMC/IntegratedTunnels-Compat/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/integrated-tunnels"
license="MIT"
logoFile="logo.png"
authors="rubensworks (aka kroeser)"
[[mods]]
modId="integratedtunnelscompat"
version="${file.jarVersion}"
displayName="IntegratedTunnels-Compat"
description='''
Integrated Tunnels compatibility with other mods.
'''
[[dependencies.integratedtunnelscompat]]
    modId="cyclopscore"
    mandatory=true
    versionRange="[1.18.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integratedtunnelscompat]]
    modId="integratedtunnels"
    mandatory=true
    versionRange="[1.8.11,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integratedtunnelscompat]]
    modId="forge"
    mandatory=true
    versionRange="[45.0.50,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integratedtunnelscompat]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,]"
    ordering="NONE"
    side="BOTH"
