modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/CyclopsMC/IntegratedTunnels-Compat/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/integrated-tunnels"
license="MIT"
logoFile="logo.png"
authors="rubensworks (aka kroeser)"
[[mods]]
modId="integratedtunnelscompat"
version="${file.jarVersion}"
displayName="IntegratedTunnels-Compat"
description='''
Integrated Tunnels compatibility with other mods.
'''
[[dependencies.integratedtunnelscompat]]
    modId="cyclopscore"
    type="required"
    versionRange="[1.19.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integratedtunnelscompat]]
    modId="integratedtunnels"
    type="required"
    versionRange="[1.8.11,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integratedtunnelscompat]]
    modId="neoforge"
    type="required"
    versionRange="[21.0.43-beta,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integratedtunnelscompat]]
    modId="minecraft"
    type="required"
    versionRange="[1.21,]"
    ordering="NONE"
    side="BOTH"
